/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ti.ego (https://sketchfab.com/ti.ego)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jumping-box-a220b8f39d854a81abd91695049e2192
Title: Jumping Box
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { Link } from 'react-router-dom'

export default function Box(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/box.glb')
  const { actions ,names} = useAnimations(animations, group)
  useEffect(()=>{
    actions[names[0]].fadeIn(5).play();
  })
  return (
        <group ref={group} {...props} dispose={null} scale={3} position={[0,-3,0]}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.002}>
          <group
            name="Cube005"
            position={[-0.001, 110.253, 0.05]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 108.545]}>
            <mesh
              name="0"
              castShadow
              receiveShadow
              geometry={nodes['0'].geometry}
              material={materials.Material}
              morphTargetDictionary={nodes['0'].morphTargetDictionary}
              morphTargetInfluences={nodes['0'].morphTargetInfluences}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/box.glb')
