

/*
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Strawbie (https://sketchfab.com/strawbie133)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/strawberry-cake-0b5e74462cac4869b6cfb64c325b6d89
Title: Strawberry Cake
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Cake(props) {
  const { nodes, materials } = useGLTF('/strawberry_cake.glb')
  const size=window.innerWidth<500?0.4:0.6;
  const ref=useRef();
  useFrame((state,delta)=>{
    ref.current.rotation.y+=delta;
  })
  return (
    <group {...props} dispose={null}>
      <group scale={size} position={[0,-1,0]} ref={ref}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cupcakepolySurface44_cupcakesprinkle2_0.geometry}
          material={materials.cupcakesprinkle2}
          position={[1.996, 0, 0]}
        />
        <group position={[-0.532, 4.362, -1.215]} rotation={[-0.097, -1.214, -0.038]} scale={0.857}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder95_purple_wax_0.geometry}
            material={materials.purple_wax}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder95_white_wick_0.geometry}
            material={materials.white_wick}
          />
        </group>
        <group position={[0.511, 4.319, -1.205]} rotation={[-0.016, 0.214, 0.008]} scale={0.809}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder96_purple_wax_0.geometry}
            material={materials.purple_wax}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder96_white_wick_0.geometry}
            material={materials.white_wick}
          />
        </group>
        <group position={[1.223, 4.291, -0.505]} rotation={[0.016, -0.489, -0.014]} scale={0.778}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder97_purple_wax_0.geometry}
            material={materials.purple_wax}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder97_white_wick_0.geometry}
            material={materials.white_wick}
          />
        </group>
        <group position={[1.273, 4.283, 0.427]} rotation={[0.012, 0.292, -0.006]} scale={0.769}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder98_purple_wax_0.geometry}
            material={materials.purple_wax}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder98_white_wick_0.geometry}
            material={materials.white_wick}
          />
        </group>
        <group position={[0.632, 4.256, 1.212]} rotation={[0.03, 0.526, -0.119]} scale={0.859}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder99_purple_wax_0.geometry}
            material={materials.purple_wax}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder99_white_wick_0.geometry}
            material={materials.white_wick}
          />
        </group>
        <group position={[-0.605, 4.171, 1.206]} rotation={[0.036, 0.699, -0.018]} scale={0.646}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder100_purple_wax_0.geometry}
            material={materials.purple_wax}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder100_white_wick_0.geometry}
            material={materials.white_wick}
          />
        </group>
        <group position={[-1.331, 4.211, 0.447]} rotation={[0.114, -1.19, 0.122]} scale={0.69}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder101_purple_wax_0.geometry}
            material={materials.purple_wax}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder101_white_wick_0.geometry}
            material={materials.white_wick}
          />
        </group>
        <group position={[-1.226, 4.286, -0.483]} rotation={[0, 0.196, 0]} scale={0.772}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder102_purple_wax_0.geometry}
            material={materials.purple_wax}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder102_white_wick_0.geometry}
            material={materials.white_wick}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder67_pink_icing_0.geometry}
          material={materials.pink_icing}
          position={[0, 1, 0]}
          scale={[3, 1, 3]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pTorus5_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[0, 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pTorus6_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[0, 4, 0]}
          scale={0.75}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube99_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[0.033, 4.321, -1.882]}
          rotation={[-3.085, -0.003, -0.084]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube100_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[1.426, 4.319, -1.271]}
          rotation={[3.088, 0.002, -0.033]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube101_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[1.9, 4.32, -0.041]}
          rotation={[3.098, 0, -0.024]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube102_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[1.565, 4.402, 1.141]}
          rotation={[3.086, 0, 0.058]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube103_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[0.012, 4.431, 1.885]}
          rotation={[-3.078, 0, -0.033]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube104_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[-1.409, 4.394, 1.252]}
          rotation={[Math.PI, 0, 0.039]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube105_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[-1.879, 4.412, -0.035]}
          rotation={[Math.PI, 0, 0.01]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube106_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[-1.37, 4.392, -1.322]}
          rotation={[Math.PI, 0, 0.009]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube107_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[1.119, 2.409, -2.296]}
          rotation={[3.052, -0.001, 0.014]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube108_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[2.549, 2.413, -0.469]}
          rotation={[3.087, 0, 0.092]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube109_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[2.347, 2.425, 1.172]}
          rotation={[3.059, 0.003, -0.035]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube110_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[1.234, 2.426, 2.365]}
          rotation={[-3.137, 0.016, -0.01]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube111_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[-1.172, 2.424, 2.334]}
          rotation={[-3.116, 0.004, 0.077]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube112_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[-2.451, 2.426, 0.838]}
          rotation={[-3.131, 0, -0.051]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube113_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[-2.334, 2.426, -1.05]}
          rotation={[3.09, 0, 0.025]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube114_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[-0.961, 2.406, -2.381]}
          rotation={[3.105, -0.002, 0.048]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder70_cream_0.geometry}
          material={materials.cream}
          position={[-1.373, 4.042, -1.322]}
          rotation={[0, 0.107, 0]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder71_cream_0.geometry}
          material={materials.cream}
          position={[0.037, 4.042, -1.904]}
          rotation={[0, -0.725, 0]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder72_cream_0.geometry}
          material={materials.cream}
          position={[1.427, 4.042, -1.302]}
          rotation={[0, 0.647, 0]}
          scale={0.275}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder73_cream_0.geometry}
          material={materials.cream}
          position={[1.878, 4.042, -0.07]}
          rotation={[0, -1.259, 0]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder74_cream_0.geometry}
          material={materials.cream}
          position={[1.543, 4.042, 1.108]}
          rotation={[0, 0.994, 0]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder75_cream_0.geometry}
          material={materials.cream}
          position={[0.037, 4.042, 1.847]}
          rotation={[0, -1.057, 0]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder76_cream_0.geometry}
          material={materials.cream}
          position={[-1.401, 4.042, 1.224]}
          rotation={[0, 1.203, 0]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder77_cream_0.geometry}
          material={materials.cream}
          position={[-1.859, 4.042, -0.035]}
          rotation={[0, -0.8, 0]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder78_cream_0.geometry}
          material={materials.cream}
          position={[-0.967, 2.081, -2.406]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder79_cream_0.geometry}
          material={materials.cream}
          position={[1.134, 2.081, -2.304]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder80_cream_0.geometry}
          material={materials.cream}
          position={[2.546, 2.081, -0.441]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder81_cream_0.geometry}
          material={materials.cream}
          position={[2.354, 2.081, 1.174]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder82_cream_0.geometry}
          material={materials.cream}
          position={[1.235, 2.081, 2.338]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder83_cream_0.geometry}
          material={materials.cream}
          position={[-1.159, 2.081, 2.327]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder84_cream_0.geometry}
          material={materials.cream}
          position={[-2.469, 2.081, 0.813]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder85_cream_0.geometry}
          material={materials.cream}
          position={[-2.345, 2.081, -1.039]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pTorus8_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[0, 3, 0]}
          scale={0.765}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cupcakesweep10_cupcakefrosting_0.geometry}
          material={materials.cupcakefrosting}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cupcakepSphere3_cupcakecherry_0.geometry}
          material={materials.cupcakecherry}
          position={[0, 0.448, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cupcakesweep11_cupcakestem_0.geometry}
          material={materials.cupcakestem}
          position={[0, 0.448, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep9_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[2.304, 1.256, -1.413]}
          rotation={[-0.218, 0.545, 0.178]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep10_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[2.519, 1.222, 0.395]}
          rotation={[0, -0.347, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep11_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[1.86, 1.274, 1.789]}
          rotation={[0, 0.244, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep12_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[0.101, 1.245, 2.591]}
          rotation={[-Math.PI, -1.012, -Math.PI]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep13_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[-1.973, 1.257, 1.696]}
          rotation={[0, 0.529, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep14_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[-2.581, 1.243, -0.163]}
          rotation={[0, -0.343, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep15_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[-1.753, 1.288, -1.833]}
          rotation={[0, 0.264, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep16_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[0.045, 1.248, -2.619]}
          rotation={[0, -0.52, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep17_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[0.776, 3.187, -1.7]}
          rotation={[0, 0.411, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep18_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[1.724, 3.187, -0.708]}
          rotation={[0, -0.62, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep19_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[1.805, 3.187, 0.571]}
          rotation={[0, 0.386, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep20_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[0.898, 3.187, 1.674]}
          rotation={[0, -0.389, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep21_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[-0.711, 3.187, 1.711]}
          rotation={[0, 0.471, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep22_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[-1.731, 3.187, 0.636]}
          rotation={[0, 0.276, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep23_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[-1.715, 3.187, -0.696]}
          rotation={[0, -0.503, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep24_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[-0.695, 3.187, -1.687]}
          rotation={[0, 0.291, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pTorus9_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[0, 1, 0]}
          scale={1.015}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube115_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[0.287, 4.258, -0.694]}
          rotation={[3.1, 0, 0]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube116_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[0.691, 4.258, -0.287]}
          rotation={[Math.PI, 0, -0.058]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube117_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[0.695, 4.258, 0.286]}
          rotation={[3.098, 0, 0.058]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube118_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[0.285, 4.258, 0.689]}
          rotation={[2.994, 0, -0.067]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube119_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[-0.287, 4.258, 0.695]}
          rotation={[-3.076, 0, 0]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube120_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[-0.694, 4.258, 0.289]}
          rotation={[-3.088, 0, -0.027]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube121_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[-0.693, 4.258, -0.286]}
          rotation={[-3.092, 0, -0.009]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube122_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[-0.287, 4.258, -0.693]}
          rotation={[Math.PI, 0, 0]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder86_cream_0.geometry}
          material={materials.cream}
          position={[0, 4, 0]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder87_cream_0.geometry}
          material={materials.cream}
          position={[0.287, 3.912, -0.693]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder88_cream_0.geometry}
          material={materials.cream}
          position={[0.693, 3.912, -0.287]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder89_cream_0.geometry}
          material={materials.cream}
          position={[0.693, 3.912, 0.287]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder90_cream_0.geometry}
          material={materials.cream}
          position={[0.287, 3.912, 0.693]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder91_cream_0.geometry}
          material={materials.cream}
          position={[-0.287, 3.912, 0.693]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder92_cream_0.geometry}
          material={materials.cream}
          position={[-0.693, 3.912, 0.287]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder93_cream_0.geometry}
          material={materials.cream}
          position={[-0.693, 3.912, -0.287]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder94_cream_0.geometry}
          material={materials.cream}
          position={[-0.287, 3.912, -0.693]}
          scale={0.3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube123_red_strawberry_0.geometry}
          material={materials.red_strawberry}
          position={[0.002, 4.362, -0.002]}
          rotation={[3.072, 0, 0.052]}
          scale={[0.583, 0.621, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep25_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[-1.249, 3.187, -0.025]}
          rotation={[0, 1.053, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep26_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[-0.927, 3.187, -0.865]}
          rotation={[0, 0.122, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep27_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[-0.001, 3.187, -1.247]}
          rotation={[0, 1.084, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep28_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[0.901, 3.187, -0.883]}
          rotation={[0, -0.312, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep29_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[1.235, 3.187, -0.048]}
          rotation={[-Math.PI, 0.989, -Math.PI]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep30_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[-0.956, 3.187, 0.796]}
          rotation={[0, -0.269, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep31_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[0.031, 3.187, 1.23]}
          rotation={[0, 1.032, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sweep32_pinker_icing_0.geometry}
          material={materials.pinker_icing}
          position={[0.988, 3.187, 0.75]}
          rotation={[0, -0.073, 0]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone1_orange_fire_0.geometry}
          material={materials.orange_fire}
          position={[-1.227, 5.303, -0.468]}
          scale={0.094}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone2_orange_fire_0.geometry}
          material={materials.orange_fire}
          position={[-0.526, 5.503, -1.291]}
          rotation={[-0.061, 0, -0.013]}
          scale={0.113}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone3_orange_fire_0.geometry}
          material={materials.orange_fire}
          position={[0.503, 5.419, -1.213]}
          rotation={[-0.014, 0, 0.008]}
          scale={0.113}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone4_orange_fire_0.geometry}
          material={materials.orange_fire}
          position={[1.232, 5.36, -0.467]}
          rotation={[0.022, 0, -0.013]}
          scale={0.113}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone5_orange_fire_0.geometry}
          material={materials.orange_fire}
          position={[1.269, 5.351, 0.448]}
          rotation={[0.01, 0, -0.006]}
          scale={0.113}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone6_orange_fire_0.geometry}
          material={materials.orange_fire}
          position={[0.743, 5.43, 1.192]}
          rotation={[-0.03, 0.003, -0.103]}
          scale={0.113}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone7_orange_fire_0.geometry}
          material={materials.orange_fire}
          position={[-0.59, 5.079, 1.243]}
          rotation={[0.025, -0.001, -0.014]}
          scale={0.113}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone8_orange_fire_0.geometry}
          material={materials.orange_fire}
          position={[-1.381, 5.174, 0.45]}
          rotation={[0.001, -0.001, 0.045]}
          scale={0.113}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/strawberry_cake.glb')