/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: KURAGE (https://sketchfab.com/czech_neko)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/birthday-cake-ce87cd933943412da5cb15cab0c50eef
Title: birthday cake
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Cake(props) {
    const customScale=window.innerWidth<800?10:18;
  const { nodes, materials } = useGLTF('/b_cake.glb')
  const ref=useRef();
  useFrame((state,delta)=>{
    ref.current.rotation.y+=delta;
  })
  return (
    <group {...props} dispose={null} ref={ref} scale={customScale} rotation={[0.5,0,0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.main}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/b_cake.glb')
