/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Aupuma (https://sketchfab.com/aupuma)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mascleta-fireworks-60e3e0cc05364cbc84eaf2d0111755eb
Title: Mascletá fireworks
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Tent(props) {
  const { nodes, materials } = useGLTF('/mascleta_fireworks.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.813, 0.212, 0.358]} rotation={[-1.577, 0.001, -1.633]} scale={1.25}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.BlocksPaper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials.BlocksPaper}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mascleta_fireworks.glb')
